package at.alpscraft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCategoryAllPropertiesEquals(PostCategory expected, PostCategory actual) {
        assertPostCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertPostCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCategoryAllUpdatablePropertiesEquals(PostCategory expected, PostCategory actual) {
        assertPostCategoryUpdatableFieldsEquals(expected, actual);
        assertPostCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCategoryAutoGeneratedPropertiesEquals(PostCategory expected, PostCategory actual) {
        assertThat(actual)
            .as("Verify PostCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCategoryUpdatableFieldsEquals(PostCategory expected, PostCategory actual) {
        assertThat(actual)
            .as("Verify PostCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCategoryUpdatableRelationshipsEquals(PostCategory expected, PostCategory actual) {
        // empty method
    }
}
