package at.alpscraft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UiSectionElementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUiSectionElementAllPropertiesEquals(UiSectionElement expected, UiSectionElement actual) {
        assertUiSectionElementAutoGeneratedPropertiesEquals(expected, actual);
        assertUiSectionElementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUiSectionElementAllUpdatablePropertiesEquals(UiSectionElement expected, UiSectionElement actual) {
        assertUiSectionElementUpdatableFieldsEquals(expected, actual);
        assertUiSectionElementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUiSectionElementAutoGeneratedPropertiesEquals(UiSectionElement expected, UiSectionElement actual) {
        assertThat(actual)
            .as("Verify UiSectionElement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUiSectionElementUpdatableFieldsEquals(UiSectionElement expected, UiSectionElement actual) {
        assertThat(actual)
            .as("Verify UiSectionElement relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUiSectionElementUpdatableRelationshipsEquals(UiSectionElement expected, UiSectionElement actual) {
        assertThat(actual)
            .as("Verify UiSectionElement relationships")
            .satisfies(a -> assertThat(a.getUiSection()).as("check uiSection").isEqualTo(expected.getUiSection()));
    }
}
