package at.alpscraft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UiSectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUiSectionAllPropertiesEquals(UiSection expected, UiSection actual) {
        assertUiSectionAutoGeneratedPropertiesEquals(expected, actual);
        assertUiSectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUiSectionAllUpdatablePropertiesEquals(UiSection expected, UiSection actual) {
        assertUiSectionUpdatableFieldsEquals(expected, actual);
        assertUiSectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUiSectionAutoGeneratedPropertiesEquals(UiSection expected, UiSection actual) {
        assertThat(actual)
            .as("Verify UiSection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUiSectionUpdatableFieldsEquals(UiSection expected, UiSection actual) {
        assertThat(actual)
            .as("Verify UiSection relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getCssClass()).as("check cssClass").isEqualTo(expected.getCssClass()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUiSectionUpdatableRelationshipsEquals(UiSection expected, UiSection actual) {
        // empty method
    }
}
